# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adderss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(max_length=20)),
                ('addersss', models.CharField(max_length=1000)),
                ('postcode', models.IntegerField(null=True)),
                ('tel', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ttxs_adders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_num', models.IntegerField(default=1)),
                ('is_select', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'ttxs_cart',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=50)),
                ('goodsimg', models.ImageField(upload_to='')),
                ('pirce', models.FloatField(max_length=10)),
                ('categoryid', models.CharField(max_length=5)),
                ('specifics', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=200)),
                ('introductions', models.CharField(max_length=1000)),
                ('recommend', models.CharField(default=0, max_length=2)),
                ('is_delect', models.CharField(default=1, max_length=2)),
            ],
            options={
                'db_table': 'ttxs_goods',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_num', models.CharField(max_length=100)),
                ('o_status', models.IntegerField(default=0)),
                ('o_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ttxs_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.Order')),
            ],
            options={
                'db_table': 'ttxs_ordergoods',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('adderss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.Adderss')),
            ],
            options={
                'db_table': 'ttxs_user',
            },
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=200)),
                ('out_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.User')),
            ],
            options={
                'db_table': 'ttxs_userticket',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.User'),
        ),
    ]
