# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
