# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0003_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adderss',
        ),
        migrations.AddField(
            model_name='adderss',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backweb.User'),
            preserve_default=False,
        ),
    ]
