# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0004_auto_20180823_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodclassname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.Goodclass'),
        ),
    ]
