# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0005_auto_20180824_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodsname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='goods',
            name='introduction',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='goods',
            name='introductions',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pirce',
            field=models.FloatField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='goods',
            name='specifics',
            field=models.CharField(max_length=500),
        ),
    ]
