# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0006_auto_20180824_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='is_delect',
            new_name='is_delete',
        ),
    ]
