# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0007_auto_20180825_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='adderss',
            name='is_default',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
