# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0008_adderss_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_money',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='goods_money',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
