# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0009_auto_20180827_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addersss',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
