# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0010_auto_20180828_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.User')),
            ],
        ),
    ]
