# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0011_user_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_visit',
            old_name='visit',
            new_name='visit_time',
        ),
    ]
