# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0013_auto_20180829_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caeimg', models.ImageField(upload_to='')),
            ],
        ),
    ]
