# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0014_carouselimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='adderss',
            name='is_select',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
