# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0015_adderss_is_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adderss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backweb.Adderss'),
            preserve_default=False,
        ),
    ]
