# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0017_auto_20180831_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addersss',
            new_name='adderss',
        ),
    ]
