# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0018_auto_20180831_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodclass',
            name='goodclassimg',
            field=models.ImageField(default=1, upload_to='type'),
            preserve_default=False,
        ),
    ]
